-- MySQL Script generated by MySQL Workbench
-- Sun Sep 25 11:24:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WorkoutAppDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WorkoutAppDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WorkoutAppDB` DEFAULT CHARACTER SET utf8 ;
USE `WorkoutAppDB` ;

-- -----------------------------------------------------
-- Table `WorkoutAppDB`.`Workout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WorkoutAppDB`.`Workout` (
  `idWorkout` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idWorkout`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkoutAppDB`.`Exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WorkoutAppDB`.`Exercise` (
  `idExercise` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `targetMuscle` VARCHAR(45) NULL,
  `exerciseType` VARCHAR(45) NULL,
  `recommendedTime` INT NULL,
  `videoLink` VARCHAR(45) NULL,
  PRIMARY KEY (`idExercise`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkoutAppDB`.`Workout_has_Exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WorkoutAppDB`.`Workout_has_Exercise` (
  `Workout_idWorkout` INT NOT NULL,
  `Exercise_idExercise` INT NOT NULL,
  `duration` VARCHAR(45) NULL,
  PRIMARY KEY (`Workout_idWorkout`, `Exercise_idExercise`),
  INDEX `fk_Workout_has_Exercise_Exercise1_idx` (`Exercise_idExercise` ASC) VISIBLE,
  INDEX `fk_Workout_has_Exercise_Workout_idx` (`Workout_idWorkout` ASC) VISIBLE,
  CONSTRAINT `fk_Workout_has_Exercise_Workout`
    FOREIGN KEY (`Workout_idWorkout`)
    REFERENCES `WorkoutAppDB`.`Workout` (`idWorkout`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Workout_has_Exercise_Exercise1`
    FOREIGN KEY (`Exercise_idExercise`)
    REFERENCES `WorkoutAppDB`.`Exercise` (`idExercise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkoutAppDB`.`Fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WorkoutAppDB`.`Fee` (
  `idFee` INT NOT NULL AUTO_INCREMENT,
  `payeeName` VARCHAR(45) NULL,
  `amountReceived` INT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idFee`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
