# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add-new-fees.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(488, 299)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.stylesheet = QtWidgets.QWidget(MainWindow)
        self.stylesheet.setStyleSheet("background: white;")
        self.stylesheet.setObjectName("stylesheet")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.stylesheet)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.content_frame = QtWidgets.QFrame(self.stylesheet)
        self.content_frame.setStyleSheet("")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.content_frame)
        self.frame.setStyleSheet("QPushButton { \n"
"border-radius: 10px;\n"
"background: #F2CEAE;\n"
"border: 2px solid #A65C1C;\n"
"padding: 5px;\n"
"padding-right: 20px;\n"
"padding-left: 20px;\n"
"background: #F2D0D0;\n"
"border: 1px solid #BF7878;\n"
"}\n"
"\n"
"QLineEdit { \n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"padding: 5px;\n"
"background: #F2D0D0;\n"
"border: 1px solid #BF7878;\n"
"}\n"
"\n"
"#add_fees_button {\n"
"background: #C3CED9;\n"
"border: 1px solid #53687F;\n"
"padding-top: 20px;\n"
"padding-bottom: 20px;\n"
"padding-left: 60px;\n"
"padding-right: 60px;\n"
"font: 70 10pt \"Segoe UI Black\";\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QLabel {\n"
"font: 10pt \"Nirmala UI\";\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.input_name = QtWidgets.QLineEdit(self.frame)
        self.input_name.setMinimumSize(QtCore.QSize(150, 0))
        self.input_name.setText("")
        self.input_name.setObjectName("input_name")
        self.verticalLayout_2.addWidget(self.input_name)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.input_amount = QtWidgets.QLineEdit(self.frame)
        self.input_amount.setObjectName("input_amount")
        self.verticalLayout_2.addWidget(self.input_amount)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.open_calendar_button = QtWidgets.QPushButton(self.frame)
        self.open_calendar_button.setObjectName("open_calendar_button")
        self.verticalLayout_2.addWidget(self.open_calendar_button, 0, QtCore.Qt.AlignHCenter)
        self.add_fees_button = QtWidgets.QPushButton(self.frame)
        self.add_fees_button.setMinimumSize(QtCore.QSize(90, 0))
        self.add_fees_button.setObjectName("add_fees_button")
        self.verticalLayout_2.addWidget(self.add_fees_button, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 3)
        self.horizontalLayout.addWidget(self.content_frame)
        self.horizontalLayout.setStretch(0, 5)
        MainWindow.setCentralWidget(self.stylesheet)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Payee\'s Name"))
        self.input_name.setPlaceholderText(_translate("MainWindow", "Input the name of the payee"))
        self.label.setText(_translate("MainWindow", "Amount Received"))
        self.input_amount.setPlaceholderText(_translate("MainWindow", "Input the amount paid by the payee"))
        self.label_2.setText(_translate("MainWindow", "Payment for which months"))
        self.open_calendar_button.setText(_translate("MainWindow", "Open Calendar"))
        self.add_fees_button.setText(_translate("MainWindow", "Add fees"))
import resources_rc
