# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create-new-exercise.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 442)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.stylesheet = QtWidgets.QWidget(MainWindow)
        self.stylesheet.setStyleSheet("background: white;")
        self.stylesheet.setObjectName("stylesheet")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.stylesheet)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.content_frame = QtWidgets.QFrame(self.stylesheet)
        self.content_frame.setStyleSheet("")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.content_frame)
        self.frame_2.setStyleSheet("QComboBox {\n"
"background: white;\n"
"border: 1px solid #BF7E7E;\n"
"padding: 3px;\n"
"border-radius: 5px;\n"
"}\n"
"QComboBox::drop-down {\n"
"background: qlineargradient(spread:pad, x1:0.54, y1:1, x2:0.494, y2:0.0113636, stop:0.340909 rgba(197, 244, 248, 227), stop:1 rgba(191, 126, 126, 191));\n"
"width: 20px;\n"
"border-left: 1px solid #BF7E7E;\n"
"}\n"
"QComboBox::down-arrow {\n"
"image: url(\":/icons/images/icons/icons8-drop-down-50.png\");\n"
"width: 30px;\n"
"height: 20px;\n"
"}\n"
"\n"
"\n"
"QPushButton { \n"
"border-radius: 10px;\n"
"background: #F2D0D0;\n"
"border: 2px solid #BF7373;\n"
"font: 70 10pt \"Segoe UI Black\";\n"
"padding: 5px;\n"
"padding-right: 20px;\n"
"padding-left: 20px;\n"
"}\n"
"\n"
"QLineEdit { \n"
"background: #F2D0D0;\n"
"border: 2px solid #BF7373;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"padding: 5px;\n"
"}\n"
"\n"
"#create_exercise_button {\n"
"background: #C3CED9;\n"
"border: 1px solid #53687F;\n"
"padding-left: 50px;\n"
"padding-right: 50px;\n"
"padding-top: 20px;\n"
"padding-bottom: 20px;\n"
"}\n"
"\n"
"#create_exercise_button:pressed {\n"
"background: #e9ab73\n"
"}\n"
"\n"
"\n"
"QLabel {\n"
"font: 10pt \"Nirmala UI\";\n"
"}\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(50, -1, 50, -1)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.input_exercise_name = QtWidgets.QLineEdit(self.frame_2)
        self.input_exercise_name.setObjectName("input_exercise_name")
        self.verticalLayout_2.addWidget(self.input_exercise_name)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.muscle_groups_combobox = QtWidgets.QComboBox(self.frame_2)
        self.muscle_groups_combobox.setMinimumSize(QtCore.QSize(150, 30))
        self.muscle_groups_combobox.setObjectName("muscle_groups_combobox")
        self.verticalLayout_2.addWidget(self.muscle_groups_combobox)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.categories_exercises_combobox = QtWidgets.QComboBox(self.frame_2)
        self.categories_exercises_combobox.setMinimumSize(QtCore.QSize(150, 30))
        self.categories_exercises_combobox.setObjectName("categories_exercises_combobox")
        self.verticalLayout_2.addWidget(self.categories_exercises_combobox)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.input_recommended_duration = QtWidgets.QLineEdit(self.frame_2)
        self.input_recommended_duration.setObjectName("input_recommended_duration")
        self.verticalLayout_2.addWidget(self.input_recommended_duration)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.input_reference_video_link = QtWidgets.QLineEdit(self.frame_2)
        self.input_reference_video_link.setObjectName("input_reference_video_link")
        self.verticalLayout_2.addWidget(self.input_reference_video_link)
        self.create_exercise_button = QtWidgets.QPushButton(self.frame_2)
        self.create_exercise_button.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button.setStyleSheet("")
        self.create_exercise_button.setFlat(False)
        self.create_exercise_button.setObjectName("create_exercise_button")
        self.verticalLayout_2.addWidget(self.create_exercise_button, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.content_frame)
        self.horizontalLayout.setStretch(0, 5)
        MainWindow.setCentralWidget(self.stylesheet)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Exercise Name"))
        self.input_exercise_name.setPlaceholderText(_translate("MainWindow", "Input name of the exercise"))
        self.label_2.setText(_translate("MainWindow", "Target muscle group"))
        self.label_3.setText(_translate("MainWindow", "Type (Category) of Exercise"))
        self.label_4.setText(_translate("MainWindow", "Recommendation duration reps"))
        self.input_recommended_duration.setPlaceholderText(_translate("MainWindow", "Input recommended duration"))
        self.label_5.setText(_translate("MainWindow", "Video link for reference"))
        self.input_reference_video_link.setPlaceholderText(_translate("MainWindow", "Input reference video link"))
        self.create_exercise_button.setText(_translate("MainWindow", "Create"))
import resources_rc
