# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create-new-workout.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 426)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.stylesheet = QtWidgets.QWidget(MainWindow)
        self.stylesheet.setStyleSheet("background: white;")
        self.stylesheet.setObjectName("stylesheet")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.stylesheet)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.content_frame = QtWidgets.QFrame(self.stylesheet)
        self.content_frame.setStyleSheet("")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.content_frame)
        self.frame_4.setStyleSheet("QLabel {\n"
"background: #F2D0D0;\n"
"padding: 10px;\n"
"border: 1px solid #BF7878;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_3.setStretch(0, 4)
        self.horizontalLayout_3.setStretch(1, 6)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame = QtWidgets.QFrame(self.content_frame)
        self.frame.setStyleSheet("/*QPushButton { \n"
"border-radius: 10px;\n"
"background: #F2D0D0;\n"
"border: 2px solid #BF7373;\n"
"font: 70 10pt \"Segoe UI Black\";\n"
"padding: 5px;\n"
"padding-right: 20px;\n"
"padding-left: 20px;\n"
"}\n"
"*/\n"
"QLineEdit { \n"
"background: #F2D0D0;\n"
"border: 2px solid #BF7373;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"padding: 5px;\n"
"}\n"
"\n"
"#add_fee_button{\n"
"background: #C3CED9;\n"
"border: 1px solid #53687F;\n"
"padding-left: 50px;\n"
"padding-right: 50px;\n"
"padding-top: 20px;\n"
"padding-bottom: 20px;\n"
"}\n"
"\n"
"QLabel {\n"
"font: 10pt \"Nirmala UI\";\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setStyleSheet("QPushButton { \n"
"background: #EADFF2;\n"
"border: 1px solid #8A6FA6;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"padding-top: 15px;\n"
"padding-bottom: 15px;\n"
"border-radius: 10px;\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("QWidget {\n"
"background: #C0E2F5;\n"
"border-left: 4px solid #3098F2;\n"
"}\n"
"QPushButton {\n"
"background: #EADFF2;\n"
"border: 1px solid #8A6FA6;\n"
"}\n"
"")
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 173, 334))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(20, -1, 20, -1)
        self.gridLayout.setHorizontalSpacing(50)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.create_exercise_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.create_exercise_button.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button.setStyleSheet("")
        self.create_exercise_button.setFlat(False)
        self.create_exercise_button.setObjectName("create_exercise_button")
        self.gridLayout.addWidget(self.create_exercise_button, 0, 0, 1, 1)
        self.create_exercise_button_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.create_exercise_button_6.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button_6.setStyleSheet("")
        self.create_exercise_button_6.setFlat(False)
        self.create_exercise_button_6.setObjectName("create_exercise_button_6")
        self.gridLayout.addWidget(self.create_exercise_button_6, 2, 0, 1, 1)
        self.create_exercise_button_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.create_exercise_button_3.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button_3.setStyleSheet("")
        self.create_exercise_button_3.setFlat(False)
        self.create_exercise_button_3.setObjectName("create_exercise_button_3")
        self.gridLayout.addWidget(self.create_exercise_button_3, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("QWidget {\n"
"background: #C0E2F5;\n"
"border-left: 4px solid #3098F2;\n"
"}\n"
"QPushButton {\n"
"background: #EADFF2;\n"
"border: 1px solid #8A6FA6;\n"
"}\n"
"")
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 109, 364))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_2.setHorizontalSpacing(50)
        self.gridLayout_2.setVerticalSpacing(30)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.create_exercise_button_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.create_exercise_button_7.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button_7.setAcceptDrops(False)
        self.create_exercise_button_7.setStyleSheet("")
        self.create_exercise_button_7.setFlat(False)
        self.create_exercise_button_7.setObjectName("create_exercise_button_7")
        self.gridLayout_2.addWidget(self.create_exercise_button_7, 0, 0, 1, 1)
        self.create_exercise_button_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.create_exercise_button_13.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button_13.setStyleSheet("")
        self.create_exercise_button_13.setFlat(False)
        self.create_exercise_button_13.setObjectName("create_exercise_button_13")
        self.gridLayout_2.addWidget(self.create_exercise_button_13, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 3, 0, 1, 1)
        self.create_exercise_button_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.create_exercise_button_9.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button_9.setStyleSheet("")
        self.create_exercise_button_9.setFlat(False)
        self.create_exercise_button_9.setObjectName("create_exercise_button_9")
        self.gridLayout_2.addWidget(self.create_exercise_button_9, 1, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setStyleSheet("QPushButton {\n"
"background: #C0E2F5;\n"
"border: none;\n"
"border-top: 1px solid black;\n"
"padding: 5px;\n"
"font: 70 8pt \"Segoe UI Black\";\n"
"color: #5F5F5F;\n"
"}\n"
"QFrame {\n"
"border: 1px solid black;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.group1_button = QtWidgets.QPushButton(self.frame_2)
        self.group1_button.setObjectName("group1_button")
        self.verticalLayout_2.addWidget(self.group1_button)
        self.group2_button = QtWidgets.QPushButton(self.frame_2)
        self.group2_button.setObjectName("group2_button")
        self.verticalLayout_2.addWidget(self.group2_button)
        self.group3_button = QtWidgets.QPushButton(self.frame_2)
        self.group3_button.setStyleSheet("background: #3098F2;\n"
"color: white;")
        self.group3_button.setObjectName("group3_button")
        self.verticalLayout_2.addWidget(self.group3_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 3, 1)
        self.create_new_exercise_button = QtWidgets.QPushButton(self.frame_3)
        self.create_new_exercise_button.setStyleSheet("QPushButton { \n"
"border-radius: 10px;\n"
"background: #F2CEAE;\n"
"border: 2px solid #A65C1C;\n"
"padding: 5px;\n"
"padding-right: 20px;\n"
"padding-left: 20px;\n"
"}\n"
"")
        self.create_new_exercise_button.setObjectName("create_new_exercise_button")
        self.gridLayout_3.addWidget(self.create_new_exercise_button, 1, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 3)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setStyleSheet("#create_button, #delete_button {\n"
"background: #C3CED9;\n"
"border: 1px solid #53687F;\n"
"font: 70 10pt \"Segoe UI Black\";\n"
"border-radius: none;\n"
"}\n"
"\n"
"QLabel { \n"
"background: #FFF7D6;\n"
"border: 1px solid #E9D59C;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"padding-top: 15px;\n"
"padding-bottom: 15px;\n"
"border-radius: 10px;\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frame_6)
        self.scrollArea_3.setStyleSheet("")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 384, 361))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_7.setSpacing(30)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_6.addWidget(self.scrollArea_3)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.create_button = QtWidgets.QPushButton(self.frame_7)
        self.create_button.setMinimumSize(QtCore.QSize(90, 0))
        self.create_button.setObjectName("create_button")
        self.verticalLayout_5.addWidget(self.create_button)
        self.delete_button = QtWidgets.QPushButton(self.frame_7)
        self.delete_button.setMinimumSize(QtCore.QSize(90, 0))
        self.delete_button.setObjectName("delete_button")
        self.verticalLayout_5.addWidget(self.delete_button)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 4)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.content_frame)
        self.horizontalLayout.setStretch(0, 5)
        MainWindow.setCentralWidget(self.stylesheet)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CHOOSE THE DESIRED EXERCISE"))
        self.label_2.setText(_translate("MainWindow", "DRAG AND DROP THE EXERCISE"))
        self.create_exercise_button.setText(_translate("MainWindow", "Exercise \n"
"1"))
        self.create_exercise_button_6.setText(_translate("MainWindow", "Exercise \n"
"3"))
        self.create_exercise_button_3.setText(_translate("MainWindow", "Exercise \n"
"2"))
        self.pushButton_2.setText(_translate("MainWindow", "Exercise\n"
"4"))
        self.create_exercise_button_7.setText(_translate("MainWindow", "Exercise \n"
"1"))
        self.create_exercise_button_13.setText(_translate("MainWindow", "Exercise \n"
"3"))
        self.pushButton.setText(_translate("MainWindow", "Exercise\n"
"4"))
        self.create_exercise_button_9.setText(_translate("MainWindow", "Exercise \n"
"2"))
        self.group1_button.setText(_translate("MainWindow", "Tab1"))
        self.group2_button.setText(_translate("MainWindow", "Tab 2"))
        self.group3_button.setText(_translate("MainWindow", "Tab 3"))
        self.create_new_exercise_button.setText(_translate("MainWindow", "Create New Exercise"))
        self.label_4.setText(_translate("MainWindow", "Exercise \n"
"(Double Click to change)"))
        self.label_3.setText(_translate("MainWindow", "Exercise \n"
" (Double click to change properties)"))
        self.label_5.setText(_translate("MainWindow", "Exercise \n"
" (Double click to change properties)"))
        self.create_button.setText(_translate("MainWindow", "Create \n"
"Workout"))
        self.delete_button.setText(_translate("MainWindow", "Delete \n"
"Workout"))
import resources_rc
