# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/exercise1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(422, 279)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.stylesheet = QtWidgets.QWidget(MainWindow)
        self.stylesheet.setStyleSheet("background: white;")
        self.stylesheet.setObjectName("stylesheet")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.stylesheet)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.content_frame = QtWidgets.QFrame(self.stylesheet)
        self.content_frame.setStyleSheet("")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.content_frame)
        self.frame.setStyleSheet("QPushButton {\n"
"background: transparent;\n"
"border: 1px solid black;\n"
"padding: 10px;\n"
"}\n"
"\n"
"QLineEdit { \n"
"border: 2px solid grey;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"padding: 5px;\n"
"}\n"
"\n"
"#add_fee_button{\n"
"background: #C3CED9;\n"
"border: 1px solid #53687F;\n"
"padding-left: 50px;\n"
"padding-right: 50px;\n"
"padding-top: 20px;\n"
"padding-bottom: 20px;\n"
"}\n"
"\n"
"QLabel {\n"
"font: 10pt \"Nirmala UI\";\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.duration_radioButton = QtWidgets.QRadioButton(self.frame)
        self.duration_radioButton.setObjectName("duration_radioButton")
        self.gridLayout.addWidget(self.duration_radioButton, 0, 0, 1, 1)
        self.input_sets = QtWidgets.QLineEdit(self.frame)
        self.input_sets.setObjectName("input_sets")
        self.gridLayout.addWidget(self.input_sets, 2, 2, 1, 1)
        self.reps_sets_radioButton = QtWidgets.QRadioButton(self.frame)
        self.reps_sets_radioButton.setObjectName("reps_sets_radioButton")
        self.gridLayout.addWidget(self.reps_sets_radioButton, 0, 1, 1, 2, QtCore.Qt.AlignLeft)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.input_reps = QtWidgets.QLineEdit(self.frame)
        self.input_reps.setObjectName("input_reps")
        self.gridLayout.addWidget(self.input_reps, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.input_duration = QtWidgets.QLineEdit(self.frame)
        self.input_duration.setObjectName("input_duration")
        self.gridLayout.addWidget(self.input_duration, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(self.frame)
        self.cancel_button.setMinimumSize(QtCore.QSize(100, 0))
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout.addWidget(self.cancel_button, 5, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.ok_button = QtWidgets.QPushButton(self.frame)
        self.ok_button.setMinimumSize(QtCore.QSize(100, 0))
        self.ok_button.setObjectName("ok_button")
        self.gridLayout.addWidget(self.ok_button, 5, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout.setColumnMinimumWidth(0, 1)
        self.gridLayout.setColumnMinimumWidth(1, 1)
        self.gridLayout.setColumnMinimumWidth(2, 2)
        self.gridLayout.setColumnStretch(0, 4)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 2)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 3)
        self.horizontalLayout.addWidget(self.content_frame)
        self.horizontalLayout.setStretch(0, 5)
        MainWindow.setCentralWidget(self.stylesheet)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.duration_radioButton.setText(_translate("MainWindow", "Duration (s)"))
        self.reps_sets_radioButton.setText(_translate("MainWindow", "Reps/Sets"))
        self.label_2.setText(_translate("MainWindow", "Sets"))
        self.label.setText(_translate("MainWindow", "Reps"))
        self.input_duration.setPlaceholderText(_translate("MainWindow", "Add the duration"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))
        self.ok_button.setText(_translate("MainWindow", "OK"))
import resources_rc
