# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exercise.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 321)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.stylesheet = QtWidgets.QWidget(MainWindow)
        self.stylesheet.setStyleSheet("background: white;")
        self.stylesheet.setObjectName("stylesheet")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.stylesheet)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.content_frame = QtWidgets.QFrame(self.stylesheet)
        self.content_frame.setStyleSheet("")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.content_frame)
        self.frame.setStyleSheet("/*QPushButton { \n"
"border-radius: 10px;\n"
"background: #F2D0D0;\n"
"border: 2px solid #BF7373;\n"
"font: 70 10pt \"Segoe UI Black\";\n"
"padding: 5px;\n"
"padding-right: 20px;\n"
"padding-left: 20px;\n"
"}\n"
"*/\n"
"\n"
"QPushButton {\n"
"background: transparent;\n"
"border: 1px solid black;\n"
"padding: 10px;\n"
"}\n"
"\n"
"QLineEdit { \n"
"background: #F2D0D0;\n"
"border: 2px solid #BF7373;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"padding: 5px;\n"
"}\n"
"\n"
"#add_fee_button{\n"
"background: #C3CED9;\n"
"border: 1px solid #53687F;\n"
"padding-left: 50px;\n"
"padding-right: 50px;\n"
"padding-top: 20px;\n"
"padding-bottom: 20px;\n"
"}\n"
"\n"
"QLabel {\n"
"font: 10pt \"Nirmala UI\";\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.exercise_type_label = QtWidgets.QLabel(self.frame)
        self.exercise_type_label.setText("")
        self.exercise_type_label.setObjectName("exercise_type_label")
        self.gridLayout.addWidget(self.exercise_type_label, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.exercise_name_label = QtWidgets.QLabel(self.frame)
        self.exercise_name_label.setText("")
        self.exercise_name_label.setObjectName("exercise_name_label")
        self.gridLayout.addWidget(self.exercise_name_label, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.target_muscle_label = QtWidgets.QLabel(self.frame)
        self.target_muscle_label.setText("")
        self.target_muscle_label.setObjectName("target_muscle_label")
        self.gridLayout.addWidget(self.target_muscle_label, 1, 1, 1, 1)
        self.recommended_time_label = QtWidgets.QLabel(self.frame)
        self.recommended_time_label.setText("")
        self.recommended_time_label.setObjectName("recommended_time_label")
        self.gridLayout.addWidget(self.recommended_time_label, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.video_link_label = QtWidgets.QLabel(self.frame)
        self.video_link_label.setText("")
        self.video_link_label.setObjectName("video_link_label")
        self.gridLayout.addWidget(self.video_link_label, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.close_button = QtWidgets.QPushButton(self.frame)
        self.close_button.setMinimumSize(QtCore.QSize(100, 0))
        self.close_button.setObjectName("close_button")
        self.gridLayout.addWidget(self.close_button, 6, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 3)
        self.horizontalLayout.addWidget(self.content_frame)
        self.horizontalLayout.setStretch(0, 5)
        MainWindow.setCentralWidget(self.stylesheet)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Recommended time:"))
        self.label.setText(_translate("MainWindow", "Exercise Name:"))
        self.label_3.setText(_translate("MainWindow", "Target Muscle:"))
        self.label_5.setText(_translate("MainWindow", "Exercise Type:"))
        self.label_9.setText(_translate("MainWindow", "Video Link:"))
        self.close_button.setText(_translate("MainWindow", "Close"))
import resources_rc
