# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fee-management.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 363)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.stylesheet = QtWidgets.QWidget(MainWindow)
        self.stylesheet.setStyleSheet("")
        self.stylesheet.setObjectName("stylesheet")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.stylesheet)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.content_frame = QtWidgets.QFrame(self.stylesheet)
        self.content_frame.setStyleSheet("")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.content_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.monthly_income_label = QtWidgets.QLabel(self.frame_2)
        self.monthly_income_label.setMinimumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.monthly_income_label.setFont(font)
        self.monthly_income_label.setStyleSheet("background: #E5DBEC;\n"
"padding: 3px;\n"
"border:1px solid #9780A6;\n"
"border-radius: 10px;")
        self.monthly_income_label.setAlignment(QtCore.Qt.AlignCenter)
        self.monthly_income_label.setObjectName("monthly_income_label")
        self.verticalLayout_2.addWidget(self.monthly_income_label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.content_frame)
        self.frame.setStyleSheet("QPushButton { \n"
"border-radius: 10px;\n"
"background: #F2D0D0;\n"
"border: 2px solid #BF7373;\n"
"font: 70 12pt \"Segoe UI Black\";\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(20, 50, 20, 50)
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.database_fee_payment_button = QtWidgets.QPushButton(self.frame)
        self.database_fee_payment_button.setMinimumSize(QtCore.QSize(0, 80))
        self.database_fee_payment_button.setStyleSheet("")
        self.database_fee_payment_button.setFlat(False)
        self.database_fee_payment_button.setObjectName("database_fee_payment_button")
        self.horizontalLayout_2.addWidget(self.database_fee_payment_button)
        self.add_fees_button = QtWidgets.QPushButton(self.frame)
        self.add_fees_button.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(8)
        self.add_fees_button.setFont(font)
        self.add_fees_button.setStyleSheet("")
        self.add_fees_button.setObjectName("add_fees_button")
        self.horizontalLayout_2.addWidget(self.add_fees_button)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        self.horizontalLayout.addWidget(self.content_frame)
        self.horizontalLayout.setStretch(0, 5)
        MainWindow.setCentralWidget(self.stylesheet)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Fee Management"))
        self.label_2.setText(_translate("MainWindow", "This month\'s income"))
        self.monthly_income_label.setText(_translate("MainWindow", "₹X"))
        self.database_fee_payment_button.setText(_translate("MainWindow", "View database of fee \n"
"payment"))
        self.add_fees_button.setText(_translate("MainWindow", "Add new fees"))
import resources_rc
