# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view-previous-workouts.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 321)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.stylesheet = QtWidgets.QWidget(MainWindow)
        self.stylesheet.setStyleSheet("background: white;")
        self.stylesheet.setObjectName("stylesheet")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.stylesheet)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.content_frame = QtWidgets.QFrame(self.stylesheet)
        self.content_frame.setStyleSheet("")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.content_frame)
        self.frame_2.setStyleSheet("QComboBox {\n"
"background: white;\n"
"border: 1px solid #BF7E7E;\n"
"padding: 3px;\n"
"border-radius: 5px;\n"
"}\n"
"QComboBox::drop-down {\n"
"background: qlineargradient(spread:pad, x1:0.54, y1:1, x2:0.494, y2:0.0113636, stop:0.340909 rgba(197, 244, 248, 227), stop:1 rgba(191, 126, 126, 191));\n"
"width: 20px;\n"
"border-left: 1px solid #BF7E7E;\n"
"}\n"
"QComboBox::down-arrow {\n"
"image: url(\":/icons/images/icons/icons8-drop-down-50.png\");\n"
"width: 30px;\n"
"height: 20px;\n"
"}\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.year_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.year_comboBox.setMinimumSize(QtCore.QSize(150, 30))
        self.year_comboBox.setObjectName("year_comboBox")
        self.gridLayout.addWidget(self.year_comboBox, 2, 1, 1, 1)
        self.month_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.month_comboBox.setMinimumSize(QtCore.QSize(150, 30))
        self.month_comboBox.setObjectName("month_comboBox")
        self.gridLayout.addWidget(self.month_comboBox, 2, 2, 1, 1)
        self.day_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.day_comboBox.setMinimumSize(QtCore.QSize(150, 30))
        self.day_comboBox.setObjectName("day_comboBox")
        self.gridLayout.addWidget(self.day_comboBox, 2, 3, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.content_frame)
        self.frame.setStyleSheet("QPushButton { \n"
"border-radius: 10px;\n"
"background: #F2D0D0;\n"
"border: 2px solid #BF7373;\n"
"font: 70 10pt \"Segoe UI Black\";\n"
"padding: 5px;\n"
"padding-right: 20px;\n"
"padding-left: 20px;\n"
"}\n"
"\n"
"QLineEdit { \n"
"background: #F2D0D0;\n"
"border: 2px solid #BF7373;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"padding: 5px;\n"
"}\n"
"\n"
"#add_fee_button{\n"
"background: #C3CED9;\n"
"border: 1px solid #53687F;\n"
"padding-left: 50px;\n"
"padding-right: 50px;\n"
"padding-top: 20px;\n"
"padding-bottom: 20px;\n"
"}\n"
"\n"
"QLabel {\n"
"font: 10pt \"Nirmala UI\";\n"
"}\n"
"\n"
"/* QTABLEWIDGET */\n"
"QTableWidget {\n"
"    background: #EBE4F2;\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QTableWidget::verticalHeader {    \n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"\n"
"\n"
"/* QHEADERVIEW */\n"
"QHeaderView {\n"
"background: #EBE4F2;\n"
"border: 1px solid #AD9BBF;\n"
"border-radius:15px;\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"background: #EBE4F2;\n"
"border: none;\n"
"border-right: 1px solid #AD9BBF;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"background: #EBE4F2;\n"
"border: none;\n"
"border-bottom: 1px solid #AD9BBF;\n"
"padding-left: 5px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(1, 3)
        self.horizontalLayout.addWidget(self.content_frame)
        self.horizontalLayout.setStretch(0, 5)
        MainWindow.setCentralWidget(self.stylesheet)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Choose the month"))
        self.label_2.setText(_translate("MainWindow", "Choose the day"))
        self.label_3.setText(_translate("MainWindow", "Choose the year"))
        self.label_4.setText(_translate("MainWindow", "Workout"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Exercises"))
import resources_rc
