# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view-all-exercises.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 321)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.stylesheet = QtWidgets.QWidget(MainWindow)
        self.stylesheet.setStyleSheet("background: white;")
        self.stylesheet.setObjectName("stylesheet")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.stylesheet)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.content_frame = QtWidgets.QFrame(self.stylesheet)
        self.content_frame.setStyleSheet("")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.content_frame)
        self.frame.setStyleSheet("/*QPushButton { \n"
"border-radius: 10px;\n"
"background: #F2D0D0;\n"
"border: 2px solid #BF7373;\n"
"font: 70 10pt \"Segoe UI Black\";\n"
"padding: 5px;\n"
"padding-right: 20px;\n"
"padding-left: 20px;\n"
"}\n"
"*/\n"
"QLineEdit { \n"
"background: #F2D0D0;\n"
"border: 2px solid #BF7373;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"padding: 5px;\n"
"}\n"
"\n"
"#add_fee_button{\n"
"background: #C3CED9;\n"
"border: 1px solid #53687F;\n"
"padding-left: 50px;\n"
"padding-right: 50px;\n"
"padding-top: 20px;\n"
"padding-bottom: 20px;\n"
"}\n"
"\n"
"QLabel {\n"
"font: 10pt \"Nirmala UI\";\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.outer_group_frame = QtWidgets.QFrame(self.frame)
        self.outer_group_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outer_group_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outer_group_frame.setObjectName("outer_group_frame")
        self.verticalLayout_outer_group = QtWidgets.QVBoxLayout(self.outer_group_frame)
        self.verticalLayout_outer_group.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_outer_group.setSpacing(0)
        self.verticalLayout_outer_group.setObjectName("verticalLayout_outer_group")
        self.group_frame = QtWidgets.QFrame(self.outer_group_frame)
        self.group_frame.setStyleSheet("QPushButton {\n"
"background: transparent;\n"
"border: none;\n"
"border-top: 1px solid black;\n"
"padding: 5px;\n"
"font: 70 8pt \"Segoe UI Black\";\n"
"color: #5F5F5F;\n"
"}\n"
"QFrame {\n"
"border: 1px solid black;\n"
"}")
        self.group_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.group_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.group_frame.setObjectName("group_frame")
        self.verticalLayout_inner_group = QtWidgets.QVBoxLayout(self.group_frame)
        self.verticalLayout_inner_group.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_inner_group.setSpacing(0)
        self.verticalLayout_inner_group.setObjectName("verticalLayout_inner_group")
        self.group1_button = QtWidgets.QPushButton(self.group_frame)
        self.group1_button.setObjectName("group1_button")
        self.verticalLayout_inner_group.addWidget(self.group1_button)
        self.group2_button = QtWidgets.QPushButton(self.group_frame)
        self.group2_button.setObjectName("group2_button")
        self.verticalLayout_inner_group.addWidget(self.group2_button)
        self.group3_button = QtWidgets.QPushButton(self.group_frame)
        self.group3_button.setStyleSheet("background: #3098F2;\n"
"color: white;")
        self.group3_button.setObjectName("group3_button")
        self.verticalLayout_inner_group.addWidget(self.group3_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_inner_group.addItem(spacerItem)
        self.group4_button = QtWidgets.QPushButton(self.group_frame)
        self.group4_button.setObjectName("group4_button")
        self.verticalLayout_inner_group.addWidget(self.group4_button)
        self.verticalLayout_outer_group.addWidget(self.group_frame)
        self.horizontalLayout_2.addWidget(self.outer_group_frame)
        self.stackedWidget_frame = QtWidgets.QFrame(self.frame)
        self.stackedWidget_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget_frame.setObjectName("stackedWidget_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.stackedWidget_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.stackedWidget_frame)
        self.stackedWidget.setStyleSheet("QPushButton { \n"
"background: #EADFF2;\n"
"border: 1px solid #8A6FA6;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"padding-top: 15px;\n"
"padding-bottom: 15px;\n"
"border-radius: 10px;\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 228, 250))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(20, -1, 20, -1)
        self.gridLayout.setHorizontalSpacing(50)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.create_exercise_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.create_exercise_button.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button.setStyleSheet("")
        self.create_exercise_button.setFlat(False)
        self.create_exercise_button.setObjectName("create_exercise_button")
        self.gridLayout.addWidget(self.create_exercise_button, 0, 0, 1, 1)
        self.create_exercise_button_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.create_exercise_button_2.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button_2.setStyleSheet("")
        self.create_exercise_button_2.setFlat(False)
        self.create_exercise_button_2.setObjectName("create_exercise_button_2")
        self.gridLayout.addWidget(self.create_exercise_button_2, 0, 1, 1, 1)
        self.create_exercise_button_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.create_exercise_button_3.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button_3.setStyleSheet("")
        self.create_exercise_button_3.setFlat(False)
        self.create_exercise_button_3.setObjectName("create_exercise_button_3")
        self.gridLayout.addWidget(self.create_exercise_button_3, 1, 0, 1, 1)
        self.create_exercise_button_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.create_exercise_button_4.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button_4.setStyleSheet("")
        self.create_exercise_button_4.setFlat(False)
        self.create_exercise_button_4.setObjectName("create_exercise_button_4")
        self.gridLayout.addWidget(self.create_exercise_button_4, 1, 1, 1, 1)
        self.create_exercise_button_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.create_exercise_button_6.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button_6.setStyleSheet("")
        self.create_exercise_button_6.setFlat(False)
        self.create_exercise_button_6.setObjectName("create_exercise_button_6")
        self.gridLayout.addWidget(self.create_exercise_button_6, 2, 0, 1, 1)
        self.create_exercise_button_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.create_exercise_button_5.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button_5.setStyleSheet("")
        self.create_exercise_button_5.setFlat(False)
        self.create_exercise_button_5.setObjectName("create_exercise_button_5")
        self.gridLayout.addWidget(self.create_exercise_button_5, 2, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 404, 255))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_2.setHorizontalSpacing(50)
        self.gridLayout_2.setVerticalSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.create_exercise_button_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.create_exercise_button_7.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button_7.setStyleSheet("")
        self.create_exercise_button_7.setFlat(False)
        self.create_exercise_button_7.setObjectName("create_exercise_button_7")
        self.gridLayout_2.addWidget(self.create_exercise_button_7, 0, 0, 1, 1)
        self.create_exercise_button_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.create_exercise_button_8.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button_8.setStyleSheet("")
        self.create_exercise_button_8.setFlat(False)
        self.create_exercise_button_8.setObjectName("create_exercise_button_8")
        self.gridLayout_2.addWidget(self.create_exercise_button_8, 0, 1, 1, 1)
        self.create_exercise_button_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.create_exercise_button_9.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button_9.setStyleSheet("")
        self.create_exercise_button_9.setFlat(False)
        self.create_exercise_button_9.setObjectName("create_exercise_button_9")
        self.gridLayout_2.addWidget(self.create_exercise_button_9, 1, 0, 1, 1)
        self.create_exercise_button_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.create_exercise_button_11.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button_11.setStyleSheet("")
        self.create_exercise_button_11.setFlat(False)
        self.create_exercise_button_11.setObjectName("create_exercise_button_11")
        self.gridLayout_2.addWidget(self.create_exercise_button_11, 1, 1, 1, 1)
        self.create_exercise_button_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.create_exercise_button_13.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button_13.setStyleSheet("")
        self.create_exercise_button_13.setFlat(False)
        self.create_exercise_button_13.setObjectName("create_exercise_button_13")
        self.gridLayout_2.addWidget(self.create_exercise_button_13, 2, 0, 1, 1)
        self.create_exercise_button_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.create_exercise_button_12.setMinimumSize(QtCore.QSize(0, 0))
        self.create_exercise_button_12.setStyleSheet("")
        self.create_exercise_button_12.setFlat(False)
        self.create_exercise_button_12.setObjectName("create_exercise_button_12")
        self.gridLayout_2.addWidget(self.create_exercise_button_12, 2, 1, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.stackedWidget_frame)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 4)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 3)
        self.horizontalLayout.addWidget(self.content_frame)
        self.horizontalLayout.setStretch(0, 5)
        MainWindow.setCentralWidget(self.stylesheet)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.group1_button.setText(_translate("MainWindow", "Group 1"))
        self.group2_button.setText(_translate("MainWindow", "Group 2"))
        self.group3_button.setText(_translate("MainWindow", "Group 3"))
        self.group4_button.setText(_translate("MainWindow", "Group 4"))
        self.create_exercise_button.setText(_translate("MainWindow", "Exercise \n"
"1"))
        self.create_exercise_button_2.setText(_translate("MainWindow", "Exercise \n"
"2"))
        self.create_exercise_button_3.setText(_translate("MainWindow", "Exercise \n"
"3"))
        self.create_exercise_button_4.setText(_translate("MainWindow", "Exercise \n"
"4"))
        self.create_exercise_button_6.setText(_translate("MainWindow", "Exercise \n"
"5"))
        self.create_exercise_button_5.setText(_translate("MainWindow", "Exercise \n"
"6"))
        self.create_exercise_button_7.setText(_translate("MainWindow", "Exercise \n"
"1"))
        self.create_exercise_button_8.setText(_translate("MainWindow", "Exercise \n"
"2"))
        self.create_exercise_button_9.setText(_translate("MainWindow", "Exercise \n"
"3"))
        self.create_exercise_button_11.setText(_translate("MainWindow", "Exercise \n"
"4"))
        self.create_exercise_button_13.setText(_translate("MainWindow", "Exercise \n"
"5"))
        self.create_exercise_button_12.setText(_translate("MainWindow", "Exercise \n"
"6"))
import resources_rc
