# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'workouts.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 402)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.stylesheet = QtWidgets.QWidget(MainWindow)
        self.stylesheet.setStyleSheet("")
        self.stylesheet.setObjectName("stylesheet")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.stylesheet)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.content_frame = QtWidgets.QFrame(self.stylesheet)
        self.content_frame.setStyleSheet("")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.content_frame)
        self.frame.setStyleSheet("QPushButton { \n"
"border-radius: 10px;\n"
"background: #F2D0D0;\n"
"border: 2px solid #BF7373;\n"
"font: 70 12pt \"Segoe UI Black\";\n"
"padding: 20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(30, 30, 30, 30)
        self.gridLayout.setSpacing(50)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.create_new_workout_button = QtWidgets.QPushButton(self.frame)
        self.create_new_workout_button.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(8)
        self.create_new_workout_button.setFont(font)
        self.create_new_workout_button.setStyleSheet("")
        self.create_new_workout_button.setObjectName("create_new_workout_button")
        self.gridLayout.addWidget(self.create_new_workout_button, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.view_previous_workout_button = QtWidgets.QPushButton(self.frame)
        self.view_previous_workout_button.setMinimumSize(QtCore.QSize(0, 100))
        self.view_previous_workout_button.setStyleSheet("")
        self.view_previous_workout_button.setObjectName("view_previous_workout_button")
        self.gridLayout.addWidget(self.view_previous_workout_button, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.view_catalog_of_exercises_button = QtWidgets.QPushButton(self.frame)
        self.view_catalog_of_exercises_button.setMinimumSize(QtCore.QSize(0, 100))
        self.view_catalog_of_exercises_button.setStyleSheet("")
        self.view_catalog_of_exercises_button.setObjectName("view_catalog_of_exercises_button")
        self.gridLayout.addWidget(self.view_catalog_of_exercises_button, 2, 1, 1, 2, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 3)
        self.horizontalLayout.addWidget(self.content_frame)
        self.horizontalLayout.setStretch(0, 5)
        MainWindow.setCentralWidget(self.stylesheet)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Please select where you want to proceed"))
        self.create_new_workout_button.setText(_translate("MainWindow", "Create new workouts"))
        self.view_previous_workout_button.setText(_translate("MainWindow", "View previous workouts"))
        self.view_catalog_of_exercises_button.setText(_translate("MainWindow", "View the catalog of exercises"))
import resources_rc
